pipeline:
  name: Build nodejs-to-do
  identifier: Build_DJR_91_nodejs_to_do_1742074678172
  projectIdentifier: ToDoApp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to Docker
                  identifier: Build_and_Push_to_Docker
                  spec:
                    connectorRef: account.djreed1991dockerregistry
                    repo: djreed1991/to-do
                    tags:
                      - latest
                      - to-do
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1742062426857
        repoName: DJR-91/nodejs-to-do
        build: <+input>
